services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    ports:
      - "8888:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: ["start-dev", "--import-realm"]
    volumes:
      - ./realm.json:/opt/keycloak/data/import/realm.json
  h2:
<<<<<<< HEAD
    image: oscarfonts/h2
=======
    image: docker.io/thomseno/h2:2.3.232
>>>>>>> f073a1d5 (usando h2:2.3.232)
    container_name: h2
    ports:
      - "9092:9092"
      - "8083:8082"
    environment:
      H2_OPTIONS: "-ifNotExists -tcp -tcpAllowOthers -tcpPort 9092 -web -webAllowOthers -webPort 8082"
